#!/bin/bash
VM_NAME="$1"
IMAGE="$(readlink -f "$2")"
IGNITION_CONFIG="$(readlink -f "$3")"
echo VM_NAME $VM_NAME
echo IMAGE $IMAGE
echo IGNITION_CONFIG $IGNITION_CONFIG
VCPUS="2"
RAM_MB="2048"
STREAM="stable"
DISK_GB="10"
# For x86 / aarch64,
IGNITION_DEVICE_ARG=(--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}")

# Setup the correct SELinux label to allow access to the config
#chcon --verbose --type svirt_home_t ${IGNITION_CONFIG}

sudo virt-install --connect="qemu:///system" --name="${VM_NAME}" --vcpus="${VCPUS}" --memory="${RAM_MB}" \
        --os-variant="fedora-coreos-$STREAM" --import --graphics=none \
        --disk="size=${DISK_GB},backing_store=${IMAGE}" \
        --network bridge=virbr0 "${IGNITION_DEVICE_ARG[@]}" --noautoconsole


